# Generated by Django 3.2.25 on 2024-09-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_department_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='p1',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='p2',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='p3',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
